export const Countries = [
 { pais: 'AFGANISTAN', iata: 'AF' },
 { pais: 'ARABIA SAUDITA', iata: 'SA' },
 { pais: 'BAHREIN', iata: 'BH' },
 { pais: 'BANGLADESH', iata: 'BD' },
 { pais: 'BHUTAN', iata: 'BT' },
 { pais: 'BRUNEI', iata: 'BN' },
 { pais: 'CAMBOYA', iata: 'KH' },
 { pais: 'COREA DEL NORTE', iata: 'KP' },
 { pais: 'COREA DEL SUR', iata: 'KR' },
 { pais: 'CHINA', iata: 'CN' },
 { pais: 'CHIPRE', iata: 'CY' },
 { pais: 'FILIPINAS', iata: 'PH' },
 { pais: 'EMIRATOS ARABES UNIDOS', iata: 'AE' },
 { pais: 'HONG KONG', iata: 'HM' },
 { pais: 'INDIA', iata: 'IN' },
 { pais: 'INDONESIA', iata: 'ID' },
 { pais: 'IRAN', iata: 'IR' },
 { pais: 'IRAQ', iata: 'IQ' },
 { pais: 'ISRAEL', iata: 'IL' },
 { pais: 'JAPON', iata: 'JP' },
 { pais: 'JORDANIA', iata: 'JO' },
 { pais: 'KUWAIT', iata: 'KW' },
 { pais: 'LAOS', iata: 'LA' },
 { pais: 'LIBANO', iata: 'LB' },
 { pais: 'MACAO', iata: 'MO' },
 { pais: 'MALASIA ORIENTAL-OCCIDENTAL', iata: 'MY' },
 { pais: 'MALDIVAS (ISLAS)', iata: 'MV' },
 { pais: 'MONGOLIA', iata: 'MN' },
 { pais: 'MYANMAR', iata: 'MM' },
 { pais: 'OMAN', iata: 'OM' },
 { pais: 'PAKISTAN', iata: 'PK' },
 { pais: 'QATAR', iata: 'QA' },
 { pais: 'SINGAPUR', iata: 'SG' },
 { pais: 'SIRIA', iata: 'SY' },
 { pais: 'SRI LANKA', iata: 'LK' },
 { pais: 'TAILANDIA', iata: 'TH' },
 { pais: 'TAIWAN', iata: 'TW' },
 { pais: 'VIETNAM', iata: 'VN' },
 { pais: 'YEMEN', iata: 'YE' },
 { pais: 'ANGUILLA', iata: 'AI' },
 { pais: 'ANTIGUA Y BARBUDA', iata: 'AG' },
 { pais: 'ANTILLAS NEERLANDESAS', iata: 'AN' },
 { pais: 'ARGENTINA', iata: 'AR' },
 { pais: 'ARUBA', iata: 'AW' },
 { pais: 'BAHAMAS', iata: 'BS' },
 { pais: 'BARBADOS', iata: 'BB' },
 { pais: 'BELICE', iata: 'BZ' },
 { pais: 'BERMUDAS', iata: 'BM' },
 { pais: 'BOLIVIA', iata: 'BO' },
 { pais: 'BRASIL', iata: 'BR' },
 { pais: 'CANADA', iata: 'CA' },
 { pais: 'COLOMBIA', iata: 'CO' },
 { pais: 'COSTA RICA', iata: 'CR' },
 { pais: 'CUBA', iata: 'CU' },
 { pais: 'CHILE', iata: 'CL' },
 { pais: 'DOMINICA', iata: 'DM' },
 { pais: 'ECUADOR', iata: 'EC' },
 { pais: 'EL SALVADOR', iata: 'SV' },
 { pais: 'ESTADOS UNIDOS DE AMERICA', iata: 'US' },
 { pais: 'GRANADA', iata: 'GD' },
 { pais: 'GROENLANDIA', iata: 'GL' },
 { pais: 'GUADALUPE', iata: 'GP' },
 { pais: 'GUATEMALA', iata: 'GT' },
 { pais: 'GUYANA', iata: 'GY' },
 { pais: 'GUAYANA FRANCESA', iata: 'GF' },
 { pais: 'HAITI', iata: 'HT' },
 { pais: 'HONDURAS', iata: 'HN' },
 { pais: 'ISLAS CAIMAN', iata: 'KY' },
 { pais: 'ISLA GEORGIAS-SANDWICH DEL SUR', iata: 'GS' },
 { pais: 'ISLAS MALVINAS', iata: 'FK' },
 { pais: 'ISLAS TURCAS Y CAICOS', iata: 'TC' },
 { pais: 'ISLAS ULTRAMARINAS DE USA', iata: 'UM' },
 { pais: 'ISLAS VIRGENES BRITANICAS', iata: 'VG' },
 { pais: 'ISLAS VIRGENES de los ESTADOS UNIDOS', iata: 'VI' },
 { pais: 'JAMAICA', iata: 'JM' },
 { pais: 'MARTINICA', iata: 'MQ' },
 { pais: 'MEXICO', iata: 'MX' },
 { pais: 'MONTSERRAT', iata: 'MS' },
 { pais: 'NICARAGUA', iata: 'NI' },
 { pais: 'PANAMA', iata: 'PA' },
 { pais: 'PARAGUAY', iata: 'PY' },
 { pais: 'PERU', iata: 'PE' },
 { pais: 'PUERTO RICO', iata: 'PR' },
 { pais: 'REPUBLICA DOMINICANA', iata: 'DO' },
 { pais: 'SAN CRISTOBAL y NEVIS', iata: 'KN' },
 { pais: 'SAN PEDRO y MIQUELON', iata: 'PM' },
 { pais: 'SANTA LUCIA', iata: 'LC' },
 { pais: 'SAN VICENTE Y LAS GRANADINAS', iata: 'VC' },
 { pais: 'SURINAN', iata: 'SR' },
 { pais: 'TRINIDAD Y TOBAGO', iata: 'TT' },
 { pais: 'URUGUAY', iata: 'UY' },
 { pais: 'VENEZUELA', iata: 'VE' },
 { pais: 'ALBANIA', iata: 'AL' },
 { pais: 'ALEMANIA', iata: 'DE' },
 { pais: 'ANDORRA', iata: 'AD' },
 { pais: 'ANT.REP.YUGOSLAVIA DE MACEDONIA', iata: 'MK' },
 { pais: 'AUSTRIA', iata: 'AT' },
 { pais: 'AZERBAIJAN', iata: 'AZ' },
 { pais: 'BELGICA', iata: 'BE' },
 { pais: 'BULGARIA', iata: 'BG' },
 { pais: 'BIOLORRUSIA', iata: 'BY' },
 { pais: 'BOSNIA-HERZEGOVINA', iata: 'BA' },
 { pais: 'CIUDAD DEL VATICANO', iata: 'VA' },
 { pais: 'CROACIA', iata: 'HR' },
 { pais: 'DINAMARCA', iata: 'DK' },
 { pais: 'ESLOVENIA', iata: 'SI' },
 { pais: 'ESPA?A', iata: 'ES' },
 { pais: 'ESTONIA', iata: 'EE' },
 { pais: 'FINLANDIA', iata: 'FI' },
 { pais: 'FRANCIA', iata: 'FR' },
 { pais: 'GEORGIA', iata: 'GE' },
 { pais: 'GIBRALTAR', iata: 'GI' },
 { pais: 'GRECIA', iata: 'GR' },
 { pais: 'GUERNESEY', iata: 'GG' },
 { pais: 'HUNGRIA', iata: 'HU' },
 { pais: 'IRLANDA', iata: 'IE' },
 { pais: 'ISLANDIA', iata: 'IS' },
 { pais: 'ISLA DE MAN', iata: 'IM' },
 { pais: 'ISLAS ALAND', iata: 'AX' },
 { pais: 'ISLAS DE FEROE', iata: 'FO' },
 { pais: 'ITALIA', iata: 'IT' },
 { pais: 'JERSEY', iata: 'JE' },
 { pais: 'KIRGUIZISTAN', iata: 'KG' },
 { pais: 'KAZAJSTAN', iata: 'KZ' },
 { pais: 'LETONIA', iata: 'LV' },
 { pais: 'LITUANIA', iata: 'LT' },
 { pais: 'LIECHTENSTEIN', iata: 'LI' },
 { pais: 'LUXEMBURGO', iata: 'LU' },
 { pais: 'MALTA', iata: 'MT' },
 { pais: 'MONACO', iata: 'MC' },
 { pais: 'MOLDAVIA', iata: 'MD' },
 { pais: 'NORUEGA', iata: 'NO' },
 { pais: 'PAISES BAJOS (HOLANDA)', iata: 'NL' },
 { pais: 'POLONIA', iata: 'PL' },
 { pais: 'PORTUGAL', iata: 'PT' },
 { pais: 'REINO UNIDO', iata: 'GB' },
 { pais: 'REPUBLICA CHECA', iata: 'CZ' },
 { pais: 'REPUBLICA ESLOVACA', iata: 'SK' },
 { pais: 'REP.FED.YUGOESLAVIA-SERBIA-MONTENEGRO', iata: 'CS' },
 { pais: 'RUMANIA', iata: 'RO' },
 { pais: 'RUSIA', iata: 'RU' },
 { pais: 'SAN MARINO', iata: 'SM' },
 { pais: 'SUECIA', iata: 'SE' },
 { pais: 'SUIZA', iata: 'CH' },
 { pais: 'TAYIKISTAN', iata: 'TJ' },
 { pais: 'TURKMENISTAN', iata: 'TM' },
 { pais: 'TURQUIA', iata: 'TR' },
 { pais: 'UCRANIA', iata: 'UA' },
 { pais: 'UZBEKISTAN', iata: 'UZ' },
 { pais: 'AUSTRALIA', iata: 'AU' },
 { pais: 'FIJI', iata: 'FJ' },
 { pais: 'ISLAS COOK', iata: 'CK' },
 { pais: 'ISLAS MARIANAS DEL NORTE', iata: 'MP' },
 { pais: 'ISLAS MARSHALL', iata: 'MH' },
 { pais: 'ISLAS WALLIS Y FUTUNA', iata: 'WF' },
 { pais: 'KIRIBATI', iata: 'KI' },
 { pais: 'MICRONESIA', iata: 'FM' },
 { pais: 'NAURU', iata: 'NR' },
 { pais: 'NUEVA CALEDONIA', iata: 'NC' },
 { pais: 'NUEVA ZELANDA', iata: 'NZ' },
 { pais: 'NUEVA ZELANDA (NEW ZEALAND)', iata: 'NZ' },
 { pais: 'PALAU', iata: 'PW' },
 { pais: 'PAPUA-NUEVA GUINEA', iata: 'PG' },
 { pais: 'PITCAIRN ISLAS', iata: 'PN' },
 { pais: 'SALOMON ISLAS', iata: 'SB' },
 { pais: 'SAMOA', iata: 'WS' },
 { pais: 'TONGA', iata: 'TO' },
 { pais: 'TUVALU', iata: 'TV' },
 { pais: 'VANUATU', iata: 'VU' },
 { pais: 'SAMOA AMERICANA', iata: 'AS' },
 { pais: 'GUAM', iata: 'GU' },
 { pais: 'ISLAS COCOS', iata: 'CC' },
 { pais: 'ISLAS DE NAVIDAD', iata: 'CX' },
 { pais: 'ISLAS HEARD Y MCDONALD', iata: 'HM' },
 { pais: 'ISLA NORFOLK', iata: 'NF' },
 { pais: 'ISLA TOKELAU', iata: 'TK' },
 { pais: 'NIUE', iata: 'NU' },
 { pais: 'POLINESIA FRANCESA', iata: 'PF' },
 { pais: 'ANGOLA', iata: 'AO' },
 { pais: 'ARGELIA', iata: 'DZ' },
 { pais: 'BENIN', iata: 'BJ' },
 { pais: 'BOTSUANA', iata: 'BW' },
 { pais: 'BURKINA-FASO', iata: 'BF' },
 { pais: 'BURKINA-FASO', iata: 'OUA' },
 { pais: 'BURUNDI', iata: 'BI' },
 { pais: 'CAMERUN', iata: 'CM' },
 { pais: 'CHAD', iata: 'TD' },
 { pais: 'COMORAS ISLAS', iata: 'KM' },
 { pais: 'CONGO', iata: 'CG' },
 { pais: 'COSTA DE MARFIL', iata: 'CI' },
 { pais: 'EGIPTO', iata: 'EG' },
 { pais: 'ERITREA', iata: 'ER' },
 { pais: 'ETIOPIA', iata: 'ET' },
 { pais: 'GABON', iata: 'GA' },
 { pais: 'GAMBIA', iata: 'GM' },
 { pais: 'GHANA', iata: 'GH' },
 { pais: 'GUINEA', iata: 'GN' },
 { pais: 'GUINEA-BISSEAU', iata: 'GW' },
 { pais: 'GUINEA ECUATORIAL', iata: 'GQ' },
 { pais: 'ISLA BOUVET', iata: 'BV' },
 { pais: 'KENIA', iata: 'KE' },
 { pais: 'LESOTO', iata: 'LS' },
 { pais: 'LIBERIA', iata: 'LR' },
 { pais: 'LIBIA', iata: 'LY' },
 { pais: 'MADAGASCAR', iata: 'MG' },
 { pais: 'MALAWI', iata: 'MW' },
 { pais: 'MALI', iata: 'ML' },
 { pais: 'MARRUECOS', iata: 'MA' },
 { pais: 'MAURICIO ISLA', iata: 'MU' },
 { pais: 'MAURITANIA', iata: 'MR' },
 { pais: 'MAYOTE', iata: 'YT' },
 { pais: 'MOZAMBIQUE', iata: 'MZ' },
 { pais: 'NAMIBIA', iata: 'NA' },
 { pais: 'NIGER', iata: 'NE' },
 { pais: 'NIGERIA', iata: 'NG' },
 { pais: 'REPUBLICA CABO VERDE', iata: 'CV' },
 { pais: 'REPUBLICA CENTRO AFRICANA', iata: 'CF' },
 { pais: 'RUANDA', iata: 'RW' },
 { pais: 'SANTA HELENA Y ASCENCION ISLA', iata: 'SH' },
 { pais: 'SANTO TOME Y PRINCIPE', iata: 'ST' },
 { pais: 'SENEGAL', iata: 'SN' },
 { pais: 'SEYCHELLES ISLA', iata: 'SC' },
 { pais: 'SIERRA LEONA', iata: 'SL' },
 { pais: 'SOMALIA', iata: 'SO' },
 { pais: 'SUDAFRICA', iata: 'ZA' },
 { pais: 'SUDAN', iata: 'SD' },
 { pais: 'SUAZILANDIA', iata: 'SZ' },
 { pais: 'TANZANIA', iata: 'TZ' },
 { pais: 'TERRITORIO BRITANICO OCEANO INDICO', iata: 'IO' },
 { pais: 'TOGO', iata: 'TG' },
 { pais: 'TUNEZ', iata: 'TN' },
 { pais: 'UGANDA', iata: 'UG' },
 { pais: 'YIBUTI', iata: 'DJ' },
 { pais: 'ZAIRE', iata: 'CD' },
 { pais: 'ZAMBIA', iata: 'ZM' },
 { pais: 'ZIMBABUE', iata: 'ZW' },
 { pais: 'NEPAL', iata: 'NP' },
 { pais: 'ESLOVAQUIA', iata: 'BTS' },
 { pais: 'ESCOCIA', iata: 'SC' },
 { pais: 'ANTILLAS MAYORES', iata: 'AM' },
 { pais: 'ANTILLAS MENORES', iata: 'AA' }
]